"datasets_names" "main_var" "num_vars_count" "source" "doc"
"1" "mtcars" "mpg" 11 "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/datasets/mtcars.html"
"2" "penguins" "bill_length_mm" 5 "https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/palmerpenguins/penguins.html"
"3" "tips" "tip" 3 "https://vincentarelbundock.github.io/Rdatasets/csv/reshape2/tips.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/reshape2/tips.html"
"4" "gtcars" "msrp" 8 "https://vincentarelbundock.github.io/Rdatasets/csv/gt/gtcars.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/gt/gtcars.html"
"5" "msleep" "awake" 5 "https://vincentarelbundock.github.io/Rdatasets/csv/ggplot2/msleep.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/ggplot2/msleep.html"
"6" "Boston" "medv" 12 "https://vincentarelbundock.github.io/Rdatasets/csv/MASS/Boston.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/MASS/Boston.html"
"7" "TeachingRatings" "eval" 6 "https://vincentarelbundock.github.io/Rdatasets/csv/AER/TeachingRatings.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/AER/TeachingRatings.html"
"8" "iris" "Sepal.Length" 4 "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/iris.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/datasets/iris.html"
"9" "airquality" "Ozone" 6 "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/airquality.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/datasets/airquality.html"
"10" "education" "Y" 5 "https://vincentarelbundock.github.io/Rdatasets/csv/robustbase/education.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/robustbase/education.html"
"11" "Affairs" "affairs" 7 "https://vincentarelbundock.github.io/Rdatasets/csv/AER/Affairs.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/AER/Affairs.html"
"12" "CASchools" "math" 11 "https://vincentarelbundock.github.io/Rdatasets/csv/AER/CASchools.csv" "https://vincentarelbundock.github.io/Rdatasets/doc/AER/CASchools.html"
